version: '2'
services:
    boncmd8-app:
        image: boncmd8
        external_links:
            - boncmd8-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/boncmd8?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    boncmd8-mysql:
        extends:
            file: mysql.yml
            service: boncmd8-mysql
